name: Avenida
favicon: null
layout_spectrum: 0.4981
typography_spectrum: 0.73414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080d13'
    - '#867966'
    - '#9aa1ae'
    - '#ebdab8'
    - '#2e6726'
  brandStrength: 0.75
  lightness: 0.6047669565305114
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
