name: Avenida
favicon: null
layout_spectrum: 0.99539
typography_spectrum: 0.73414
title: Avenida
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4e4b4c'
    - '#dadada'
    - '#2d2a2b'
    - '#6e6b6c'
  brandStrength: 1
  lightness: 0.6047669565305114
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
