name: Avenida
favicon: null
layout_spectrum: 0.9731214095372707
typography_spectrum: 0.7506258182693273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.45309473667293787
  lightness: 0.6047669565305114
  saturation: 0.030907013453543186
  rhythmicContrast: 0.7869273014366627
purpose: []
