name: Avenida
favicon: null
layout_spectrum: 0.4981
typography_spectrum: 0.73414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#393738'
    - '#b8b7b7'
    - '#7d7b7c'
    - '#dddcdc'
  brandStrength: 0.4375
  lightness: 0.6047669565305114
  saturation: 0.030907013453543186
  rhythmicContrast: 0.7869273014366627
purpose: []
